/** 50 languages supported by VoiceBridge */
export const LANGUAGES = [
  { code: 'en', name: 'English',    flag: '🇬🇧' },
  { code: 'tr', name: 'Turkish',    flag: '🇹🇷' },
  { code: 'fr', name: 'French',     flag: '🇫🇷' },
  { code: 'de', name: 'German',     flag: '🇩🇪' },
  { code: 'es', name: 'Spanish',    flag: '🇪🇸' },
  { code: 'it', name: 'Italian',    flag: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹' },
  { code: 'nl', name: 'Dutch',      flag: '🇳🇱' },
  { code: 'pl', name: 'Polish',     flag: '🇵🇱' },
  { code: 'ru', name: 'Russian',    flag: '🇷🇺' },
  { code: 'uk', name: 'Ukrainian',  flag: '🇺🇦' },
  { code: 'cs', name: 'Czech',      flag: '🇨🇿' },
  { code: 'sk', name: 'Slovak',     flag: '🇸🇰' },
  { code: 'hu', name: 'Hungarian',  flag: '🇭🇺' },
  { code: 'ro', name: 'Romanian',   flag: '🇷🇴' },
  { code: 'bg', name: 'Bulgarian',  flag: '🇧🇬' },
  { code: 'hr', name: 'Croatian',   flag: '🇭🇷' },
  { code: 'sr', name: 'Serbian',    flag: '🇷🇸' },
  { code: 'el', name: 'Greek',      flag: '🇬🇷' },
  { code: 'sv', name: 'Swedish',    flag: '🇸🇪' },
  { code: 'no', name: 'Norwegian',  flag: '🇳🇴' },
  { code: 'da', name: 'Danish',     flag: '🇩🇰' },
  { code: 'fi', name: 'Finnish',    flag: '🇫🇮' },
  { code: 'ar', name: 'Arabic',     flag: '🇸🇦' },
  { code: 'he', name: 'Hebrew',     flag: '🇮🇱' },
  { code: 'fa', name: 'Persian',    flag: '🇮🇷' },
  { code: 'hi', name: 'Hindi',      flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali',    flag: '🇧🇩' },
  { code: 'ur', name: 'Urdu',       flag: '🇵🇰' },
  { code: 'ta', name: 'Tamil',      flag: '🇮🇳' },
  { code: 'te', name: 'Telugu',     flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam',  flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati',   flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi',    flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi',    flag: '🇮🇳' },
  { code: 'zh', name: 'Chinese (Simplified)', flag: '🇨🇳' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', flag: '🇹🇼' },
  { code: 'ja', name: 'Japanese',   flag: '🇯🇵' },
  { code: 'ko', name: 'Korean',     flag: '🇰🇷' },
  { code: 'th', name: 'Thai',       flag: '🇹🇭' },
  { code: 'vi', name: 'Vietnamese', flag: '🇻🇳' },
  { code: 'id', name: 'Indonesian', flag: '🇮🇩' },
  { code: 'ms', name: 'Malay',      flag: '🇲🇾' },
  { code: 'tl', name: 'Filipino',   flag: '🇵🇭' },
  { code: 'sw', name: 'Swahili',    flag: '🇰🇪' },
  { code: 'af', name: 'Afrikaans',  flag: '🇿🇦' },
  { code: 'sq', name: 'Albanian',   flag: '🇦🇱' },
  { code: 'ca', name: 'Catalan',    flag: '🏴' },
  { code: 'lv', name: 'Latvian',    flag: '🇱🇻' },
  { code: 'lt', name: 'Lithuanian', flag: '🇱🇹' },
];
