/** 100 languages supported by VoiceBridge */
export const LANGUAGES = [
  // ── Tier 1: Major world languages ────────────────────────────────────────
  { code: 'en',    name: 'English',               flag: '🇬🇧' },
  { code: 'tr',    name: 'Turkish',               flag: '🇹🇷' },
  { code: 'fr',    name: 'French',                flag: '🇫🇷' },
  { code: 'de',    name: 'German',                flag: '🇩🇪' },
  { code: 'es',    name: 'Spanish',               flag: '🇪🇸' },
  { code: 'it',    name: 'Italian',               flag: '🇮🇹' },
  { code: 'pt',    name: 'Portuguese',            flag: '🇵🇹' },
  { code: 'nl',    name: 'Dutch',                 flag: '🇳🇱' },
  { code: 'pl',    name: 'Polish',                flag: '🇵🇱' },
  { code: 'ru',    name: 'Russian',               flag: '🇷🇺' },
  // ── Tier 2: European ─────────────────────────────────────────────────────
  { code: 'uk',    name: 'Ukrainian',             flag: '🇺🇦' },
  { code: 'cs',    name: 'Czech',                 flag: '🇨🇿' },
  { code: 'sk',    name: 'Slovak',                flag: '🇸🇰' },
  { code: 'hu',    name: 'Hungarian',             flag: '🇭🇺' },
  { code: 'ro',    name: 'Romanian',              flag: '🇷🇴' },
  { code: 'bg',    name: 'Bulgarian',             flag: '🇧🇬' },
  { code: 'hr',    name: 'Croatian',              flag: '🇭🇷' },
  { code: 'sr',    name: 'Serbian',               flag: '🇷🇸' },
  { code: 'el',    name: 'Greek',                 flag: '🇬🇷' },
  { code: 'sv',    name: 'Swedish',               flag: '🇸🇪' },
  { code: 'no',    name: 'Norwegian',             flag: '🇳🇴' },
  { code: 'da',    name: 'Danish',                flag: '🇩🇰' },
  { code: 'fi',    name: 'Finnish',               flag: '🇫🇮' },
  { code: 'lv',    name: 'Latvian',               flag: '🇱🇻' },
  { code: 'lt',    name: 'Lithuanian',            flag: '🇱🇹' },
  { code: 'et',    name: 'Estonian',              flag: '🇪🇪' },
  { code: 'sl',    name: 'Slovenian',             flag: '🇸🇮' },
  { code: 'mk',    name: 'Macedonian',            flag: '🇲🇰' },
  { code: 'bs',    name: 'Bosnian',               flag: '🇧🇦' },
  { code: 'sq',    name: 'Albanian',              flag: '🇦🇱' },
  { code: 'is',    name: 'Icelandic',             flag: '🇮🇸' },
  { code: 'mt',    name: 'Maltese',               flag: '🇲🇹' },
  { code: 'cy',    name: 'Welsh',                 flag: '🏴' },
  { code: 'ga',    name: 'Irish',                 flag: '🇮🇪' },
  { code: 'gd',    name: 'Scottish Gaelic',       flag: '🏴' },
  { code: 'lb',    name: 'Luxembourgish',         flag: '🇱🇺' },
  { code: 'be',    name: 'Belarusian',            flag: '🇧🇾' },
  { code: 'ca',    name: 'Catalan',               flag: '🏴' },
  { code: 'gl',    name: 'Galician',              flag: '🇪🇸' },
  { code: 'eu',    name: 'Basque',                flag: '🏴' },
  { code: 'fo',    name: 'Faroese',               flag: '🇫🇴' },
  // ── Tier 3: Middle East & Caucasus ───────────────────────────────────────
  { code: 'ar',    name: 'Arabic',                flag: '🇸🇦' },
  { code: 'he',    name: 'Hebrew',                flag: '🇮🇱' },
  { code: 'fa',    name: 'Persian',               flag: '🇮🇷' },
  { code: 'ku',    name: 'Kurdish',               flag: '🇮🇶' },
  { code: 'ps',    name: 'Pashto',                flag: '🇦🇫' },
  { code: 'ka',    name: 'Georgian',              flag: '🇬🇪' },
  { code: 'hy',    name: 'Armenian',              flag: '🇦🇲' },
  { code: 'az',    name: 'Azerbaijani',           flag: '🇦🇿' },
  // ── Tier 4: Central & South Asia ─────────────────────────────────────────
  { code: 'hi',    name: 'Hindi',                 flag: '🇮🇳' },
  { code: 'bn',    name: 'Bengali',               flag: '🇧🇩' },
  { code: 'ur',    name: 'Urdu',                  flag: '🇵🇰' },
  { code: 'ta',    name: 'Tamil',                 flag: '🇮🇳' },
  { code: 'te',    name: 'Telugu',                flag: '🇮🇳' },
  { code: 'ml',    name: 'Malayalam',             flag: '🇮🇳' },
  { code: 'gu',    name: 'Gujarati',              flag: '🇮🇳' },
  { code: 'mr',    name: 'Marathi',               flag: '🇮🇳' },
  { code: 'pa',    name: 'Punjabi',               flag: '🇮🇳' },
  { code: 'ne',    name: 'Nepali',                flag: '🇳🇵' },
  { code: 'si',    name: 'Sinhala',               flag: '🇱🇰' },
  { code: 'sd',    name: 'Sindhi',                flag: '🇵🇰' },
  { code: 'kk',    name: 'Kazakh',                flag: '🇰🇿' },
  { code: 'uz',    name: 'Uzbek',                 flag: '🇺🇿' },
  { code: 'tk',    name: 'Turkmen',               flag: '🇹🇲' },
  { code: 'ky',    name: 'Kyrgyz',                flag: '🇰🇬' },
  { code: 'tg',    name: 'Tajik',                 flag: '🇹🇯' },
  // ── Tier 5: East & Southeast Asia ────────────────────────────────────────
  { code: 'zh',    name: 'Chinese (Simplified)',  flag: '🇨🇳' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', flag: '🇹🇼' },
  { code: 'ja',    name: 'Japanese',              flag: '🇯🇵' },
  { code: 'ko',    name: 'Korean',                flag: '🇰🇷' },
  { code: 'mn',    name: 'Mongolian',             flag: '🇲🇳' },
  { code: 'th',    name: 'Thai',                  flag: '🇹🇭' },
  { code: 'vi',    name: 'Vietnamese',            flag: '🇻🇳' },
  { code: 'id',    name: 'Indonesian',            flag: '🇮🇩' },
  { code: 'ms',    name: 'Malay',                 flag: '🇲🇾' },
  { code: 'tl',    name: 'Filipino',              flag: '🇵🇭' },
  { code: 'my',    name: 'Burmese',               flag: '🇲🇲' },
  { code: 'km',    name: 'Khmer',                 flag: '🇰🇭' },
  { code: 'lo',    name: 'Lao',                   flag: '🇱🇦' },
  { code: 'su',    name: 'Sundanese',             flag: '🇮🇩' },
  { code: 'jv',    name: 'Javanese',              flag: '🇮🇩' },
  { code: 'ceb',   name: 'Cebuano',               flag: '🇵🇭' },
  // ── Tier 6: Africa ───────────────────────────────────────────────────────
  { code: 'sw',    name: 'Swahili',               flag: '🇰🇪' },
  { code: 'af',    name: 'Afrikaans',             flag: '🇿🇦' },
  { code: 'am',    name: 'Amharic',               flag: '🇪🇹' },
  { code: 'so',    name: 'Somali',                flag: '🇸🇴' },
  { code: 'ha',    name: 'Hausa',                 flag: '🇳🇬' },
  { code: 'yo',    name: 'Yoruba',                flag: '🇳🇬' },
  { code: 'ig',    name: 'Igbo',                  flag: '🇳🇬' },
  { code: 'zu',    name: 'Zulu',                  flag: '🇿🇦' },
  { code: 'xh',    name: 'Xhosa',                 flag: '🇿🇦' },
  { code: 'rw',    name: 'Kinyarwanda',           flag: '🇷🇼' },
  { code: 'sn',    name: 'Shona',                 flag: '🇿🇼' },
  { code: 'mg',    name: 'Malagasy',              flag: '🇲🇬' },
  { code: 'ny',    name: 'Chichewa',              flag: '🇲🇼' },
  { code: 'st',    name: 'Sesotho',               flag: '🇿🇦' },
  // ── Tier 7: Other ─────────────────────────────────────────────────────────
  { code: 'ht',    name: 'Haitian Creole',        flag: '🇭🇹' },
  { code: 'mi',    name: 'Maori',                 flag: '🇳🇿' },
  { code: 'eo',    name: 'Esperanto',             flag: '🌐' },
  { code: 'ug',    name: 'Uyghur',                flag: '🇨🇳' },
];
